-- 001_database_setup.sql
-- PostgreSQL/Supabase schema for Roho.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS staff_roles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_key varchar(60) NOT NULL UNIQUE,
  role_name varchar(120) NOT NULL,
  description text,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staff_users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name varchar(160) NOT NULL,
  email varchar(254) NOT NULL UNIQUE,
  password_hash varchar(255) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  last_login_at timestamp,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_staff_users_active ON staff_users (is_active);

CREATE TABLE IF NOT EXISTS staff_user_roles (
  staff_user_id integer NOT NULL REFERENCES staff_users(id),
  role_id integer NOT NULL REFERENCES staff_roles(id),
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (staff_user_id, role_id)
);

CREATE TABLE IF NOT EXISTS staff_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_user_id integer NOT NULL REFERENCES staff_users(id),
  token_hash char(64) NOT NULL UNIQUE,
  expires_at timestamp NOT NULL,
  revoked_at timestamp,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_staff_sessions_user ON staff_sessions (staff_user_id);
CREATE INDEX IF NOT EXISTS idx_staff_sessions_expires ON staff_sessions (expires_at);

CREATE TABLE IF NOT EXISTS staff_login_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(254) NOT NULL,
  ip_address varchar(80),
  succeeded boolean NOT NULL DEFAULT false,
  failure_reason varchar(160),
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_staff_login_attempts_email_created ON staff_login_attempts (email, created_at);

CREATE TABLE IF NOT EXISTS property_collections (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug varchar(120) NOT NULL UNIQUE,
  title varchar(160) NOT NULL,
  description text NOT NULL,
  status varchar(40) NOT NULL DEFAULT 'published',
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS properties (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug varchar(120) NOT NULL UNIQUE,
  collection_id integer REFERENCES property_collections(id) ON DELETE SET NULL,
  title varchar(180) NOT NULL,
  property_type varchar(80) NOT NULL,
  bedrooms integer,
  status varchar(40) NOT NULL DEFAULT 'published',
  price_label varchar(160),
  hero_image varchar(500),
  description text NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_properties_status ON properties (status);
CREATE INDEX IF NOT EXISTS idx_properties_type ON properties (property_type);
CREATE INDEX IF NOT EXISTS idx_properties_search_trgm ON properties USING gin ((title || ' ' || description) gin_trgm_ops);

CREATE TABLE IF NOT EXISTS property_features (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id integer NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  feature varchar(180) NOT NULL,
  sort_order integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS property_media (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id integer NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  media_type varchar(30) NOT NULL DEFAULT 'image',
  url varchar(500) NOT NULL,
  alt_text varchar(255),
  is_primary boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS floor_plans (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id integer NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  name varchar(160) NOT NULL,
  bedrooms integer,
  size_sqm numeric(10, 2),
  url varchar(500),
  sort_order integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS masterplan_zones (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug varchar(120) NOT NULL UNIQUE,
  title varchar(160) NOT NULL,
  description text NOT NULL,
  image_url varchar(500),
  related_collections jsonb DEFAULT '[]'::jsonb,
  status varchar(40) NOT NULL DEFAULT 'published',
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS amenities (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug varchar(120) NOT NULL UNIQUE,
  title varchar(160) NOT NULL,
  description text,
  image_url varchar(500),
  status varchar(40) NOT NULL DEFAULT 'published',
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS property_amenities (
  property_id integer NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  amenity_id integer NOT NULL REFERENCES amenities(id) ON DELETE CASCADE,
  PRIMARY KEY (property_id, amenity_id)
);

CREATE TABLE IF NOT EXISTS anonymous_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anonymous_session_id varchar(120) NOT NULL UNIQUE,
  first_visit_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  landing_page varchar(300),
  referral_url varchar(500),
  utm_source varchar(80),
  utm_medium varchar(80),
  utm_campaign varchar(120),
  utm_content varchar(120),
  utm_term varchar(120)
);

CREATE TABLE IF NOT EXISTS session_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anonymous_session_id varchar(120) NOT NULL,
  event_type varchar(80) NOT NULL,
  page_path varchar(300),
  metadata jsonb,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_session_events_session ON session_events (anonymous_session_id);

CREATE TABLE IF NOT EXISTS enquiry_reference_sequence (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name varchar(160) NOT NULL,
  email varchar(254),
  phone varchar(40),
  country varchar(100),
  preferred_language varchar(60),
  preferred_contact_method varchar(60),
  marketing_consent boolean NOT NULL DEFAULT false,
  privacy_consent boolean NOT NULL DEFAULT true,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_customers_email ON customers (email);
CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers (phone);
CREATE INDEX IF NOT EXISTS idx_customers_created ON customers (created_at);

CREATE TABLE IF NOT EXISTS leads (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_number varchar(40) UNIQUE,
  customer_id integer REFERENCES customers(id) ON DELETE SET NULL,
  anonymous_session_id varchar(120),
  property_id integer REFERENCES properties(id) ON DELETE SET NULL,
  name varchar(160),
  email varchar(254),
  phone varchar(40),
  property_interest varchar(180),
  property_interests jsonb DEFAULT '[]'::jsonb,
  collection_interests jsonb DEFAULT '[]'::jsonb,
  bedroom_preference varchar(80),
  budget_range varchar(100),
  buying_purpose varchar(120),
  purchase_timeframe varchar(80),
  score integer NOT NULL DEFAULT 0,
  lead_score integer NOT NULL DEFAULT 0,
  follow_up_status varchar(80) NOT NULL DEFAULT 'new',
  lead_status varchar(80) NOT NULL DEFAULT 'New',
  source_platform varchar(80),
  campaign_name varchar(120),
  utm_source varchar(80),
  utm_medium varchar(80),
  utm_campaign varchar(120),
  utm_content varchar(120),
  utm_term varchar(120),
  landing_page varchar(300),
  referral_url varchar(500),
  assigned_salesperson_id integer REFERENCES staff_users(id) ON DELETE SET NULL,
  next_follow_up_at timestamp,
  last_contacted_at timestamp,
  last_activity_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads (lead_status);
CREATE INDEX IF NOT EXISTS idx_leads_follow_up_status ON leads (follow_up_status);
CREATE INDEX IF NOT EXISTS idx_leads_assigned ON leads (assigned_salesperson_id);
CREATE INDEX IF NOT EXISTS idx_leads_next_follow_up ON leads (next_follow_up_at);
CREATE INDEX IF NOT EXISTS idx_leads_source ON leads (source_platform);
CREATE INDEX IF NOT EXISTS idx_leads_utm_campaign ON leads (utm_campaign);
CREATE INDEX IF NOT EXISTS idx_leads_anonymous_session ON leads (anonymous_session_id);
CREATE INDEX IF NOT EXISTS idx_leads_created ON leads (created_at);
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads (email);
CREATE INDEX IF NOT EXISTS idx_leads_phone ON leads (phone);
CREATE INDEX IF NOT EXISTS idx_leads_status_score ON leads (lead_status, lead_score);

CREATE TABLE IF NOT EXISTS enquiries (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_number varchar(40) UNIQUE,
  lead_id integer NOT NULL REFERENCES leads(id),
  enquiry_type varchar(80) NOT NULL,
  property_id integer REFERENCES properties(id) ON DELETE SET NULL,
  message text,
  preferred_contact_time varchar(120),
  payload jsonb,
  score integer NOT NULL DEFAULT 0,
  follow_up_status varchar(80),
  notification_status varchar(80),
  status varchar(60) NOT NULL DEFAULT 'new',
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_enquiries_type ON enquiries (enquiry_type);
CREATE INDEX IF NOT EXISTS idx_enquiries_created ON enquiries (created_at);
CREATE INDEX IF NOT EXISTS idx_enquiries_status_created ON enquiries (status, created_at);

CREATE TABLE IF NOT EXISTS brochure_requests (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id integer NOT NULL REFERENCES leads(id),
  enquiry_id integer REFERENCES enquiries(id) ON DELETE SET NULL,
  property_id integer REFERENCES properties(id) ON DELETE SET NULL,
  delivery_method varchar(30),
  delivery_status varchar(30) NOT NULL DEFAULT 'pending',
  delivered_at timestamp,
  status varchar(60) NOT NULL DEFAULT 'new',
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS consultations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id integer NOT NULL REFERENCES leads(id),
  enquiry_id integer REFERENCES enquiries(id) ON DELETE SET NULL,
  preferred_date varchar(60),
  status varchar(60) NOT NULL DEFAULT 'new',
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS site_visits (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id integer NOT NULL REFERENCES leads(id),
  enquiry_id integer REFERENCES enquiries(id) ON DELETE SET NULL,
  preferred_date varchar(60),
  number_of_guests integer,
  status varchar(60) NOT NULL DEFAULT 'new',
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lead_activities (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id integer NOT NULL REFERENCES leads(id),
  reference_number varchar(40),
  activity_type varchar(80) NOT NULL,
  summary text NOT NULL,
  campaign jsonb,
  created_by_staff_id integer REFERENCES staff_users(id) ON DELETE SET NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_lead_activities_lead ON lead_activities (lead_id);

CREATE TABLE IF NOT EXISTS lead_notes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id integer NOT NULL REFERENCES leads(id),
  note text NOT NULL,
  created_by_staff_id integer NOT NULL REFERENCES staff_users(id),
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lead_assignments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id integer NOT NULL REFERENCES leads(id),
  assigned_to_staff_id integer NOT NULL REFERENCES staff_users(id),
  assigned_by_staff_id integer NOT NULL REFERENCES staff_users(id),
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lead_follow_ups (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id integer NOT NULL REFERENCES leads(id),
  assigned_to_staff_id integer REFERENCES staff_users(id) ON DELETE SET NULL,
  due_at timestamp NOT NULL,
  status varchar(60) NOT NULL DEFAULT 'pending',
  outcome text,
  completed_at timestamp,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_lead_follow_ups_due ON lead_follow_ups (due_at);
CREATE INDEX IF NOT EXISTS idx_lead_follow_ups_status ON lead_follow_ups (status);
CREATE INDEX IF NOT EXISTS idx_follow_ups_staff_due ON lead_follow_ups (assigned_to_staff_id, due_at);

CREATE TABLE IF NOT EXISTS campaigns (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_platform varchar(80) NOT NULL,
  campaign_name varchar(120),
  utm_source varchar(80),
  utm_medium varchar(80),
  utm_campaign varchar(120),
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (source_platform, utm_source, utm_medium, utm_campaign)
);

CREATE TABLE IF NOT EXISTS campaign_visits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id bigint REFERENCES campaigns(id) ON DELETE SET NULL,
  anonymous_session_id varchar(120) NOT NULL,
  landing_page varchar(300),
  referral_url varchar(500),
  first_visit_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS campaign_conversions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_visit_id bigint REFERENCES campaign_visits(id) ON DELETE SET NULL,
  lead_id integer NOT NULL REFERENCES leads(id),
  conversion_type varchar(80) NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS conversations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id integer REFERENCES leads(id) ON DELETE SET NULL,
  anonymous_session_id varchar(120),
  external_conversation_id varchar(160),
  channel varchar(40) NOT NULL,
  status varchar(60) NOT NULL DEFAULT 'open',
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_conversations_session ON conversations (anonymous_session_id);
CREATE INDEX IF NOT EXISTS idx_conversations_external ON conversations (external_conversation_id);

CREATE TABLE IF NOT EXISTS messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  sender_type varchar(40) NOT NULL,
  message_text text NOT NULL,
  metadata jsonb,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_feedback (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  rating varchar(40),
  comment text,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS knowledge_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id varchar(160) NOT NULL,
  version varchar(60) NOT NULL DEFAULT 'v1',
  title varchar(180) NOT NULL,
  status varchar(40) NOT NULL DEFAULT 'draft',
  channel varchar(40) NOT NULL DEFAULT 'public',
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (document_id, version)
);

CREATE TABLE IF NOT EXISTS knowledge_chunks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  knowledge_document_id bigint REFERENCES knowledge_documents(id) ON DELETE SET NULL,
  document_id varchar(160) NOT NULL UNIQUE,
  answer text NOT NULL,
  actions jsonb,
  content text NOT NULL,
  status varchar(40) NOT NULL DEFAULT 'approved',
  channel varchar(40) NOT NULL DEFAULT 'public',
  active boolean NOT NULL DEFAULT true,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_knowledge_content_trgm ON knowledge_chunks USING gin (content gin_trgm_ops);

CREATE TABLE IF NOT EXISTS knowledge_sync_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status varchar(60) NOT NULL,
  summary text,
  started_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at timestamp
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_staff_id integer REFERENCES staff_users(id) ON DELETE SET NULL,
  action varchar(120) NOT NULL,
  entity_type varchar(80) NOT NULL,
  entity_id varchar(80) NOT NULL,
  before_json jsonb,
  after_json jsonb,
  ip_address varchar(80),
  user_agent varchar(300),
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor ON audit_logs (actor_staff_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs (entity_type, entity_id);

CREATE TABLE IF NOT EXISTS staff_password_reset_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_user_id integer NOT NULL REFERENCES staff_users(id) ON DELETE CASCADE,
  token_hash char(64) NOT NULL UNIQUE,
  expires_at timestamp NOT NULL,
  used_at timestamp,
  revoked_at timestamp,
  requested_ip varchar(80),
  requested_user_agent varchar(300),
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_staff_password_reset_tokens_token_hash ON staff_password_reset_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_staff_password_reset_tokens_staff_user_id ON staff_password_reset_tokens (staff_user_id);
CREATE INDEX IF NOT EXISTS idx_staff_password_reset_tokens_expires_at ON staff_password_reset_tokens (expires_at);

CREATE TABLE IF NOT EXISTS staff_account_recovery_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_number varchar(32) NOT NULL UNIQUE,
  full_name varchar(160) NOT NULL,
  known_email varchar(254),
  phone varchar(60) NOT NULL,
  staff_identifier varchar(120),
  department varchar(120),
  claimed_role varchar(120),
  recovery_reason varchar(80) NOT NULL,
  preferred_contact_method varchar(40) NOT NULL,
  message text,
  status varchar(40) NOT NULL DEFAULT 'pending',
  assigned_admin_id integer REFERENCES staff_users(id) ON DELETE SET NULL,
  resolution_note text,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  resolved_at timestamp,
  CONSTRAINT chk_staff_account_recovery_status
    CHECK (status IN ('pending', 'under_review', 'awaiting_verification', 'approved', 'resolved', 'rejected'))
);
CREATE INDEX IF NOT EXISTS idx_staff_account_recovery_reference_number ON staff_account_recovery_requests (reference_number);
CREATE INDEX IF NOT EXISTS idx_staff_account_recovery_status ON staff_account_recovery_requests (status);
CREATE INDEX IF NOT EXISTS idx_staff_account_recovery_created_at ON staff_account_recovery_requests (created_at);
CREATE INDEX IF NOT EXISTS idx_staff_account_recovery_assigned_admin_id ON staff_account_recovery_requests (assigned_admin_id);

CREATE TABLE IF NOT EXISTS newsletter_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(254) NOT NULL UNIQUE,
  status varchar(40) NOT NULL DEFAULT 'active',
  source_page varchar(255),
  anonymous_session_id varchar(120),
  utm_source varchar(120),
  utm_medium varchar(120),
  utm_campaign varchar(160),
  utm_content varchar(160),
  consent boolean NOT NULL DEFAULT false,
  subscribed_at timestamp,
  unsubscribed_at timestamp,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_newsletter_subscriptions_status
    CHECK (status IN ('active', 'unsubscribed', 'suppressed'))
);
CREATE INDEX IF NOT EXISTS idx_newsletter_subscriptions_status ON newsletter_subscriptions (status);
CREATE INDEX IF NOT EXISTS idx_newsletter_subscriptions_subscribed_at ON newsletter_subscriptions (subscribed_at);
CREATE INDEX IF NOT EXISTS idx_newsletter_subscriptions_utm_campaign ON newsletter_subscriptions (utm_campaign);

CREATE TABLE IF NOT EXISTS brochure_delivery_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_number varchar(40) NOT NULL,
  enquiry_id integer REFERENCES enquiries(id) ON DELETE SET NULL,
  lead_id integer NOT NULL REFERENCES leads(id),
  delivery_method varchar(30) NOT NULL CHECK (delivery_method IN ('email', 'whatsapp')),
  recipient varchar(254) NOT NULL,
  provider varchar(60) NOT NULL,
  status varchar(30) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed', 'skipped')),
  provider_message_id varchar(190),
  error_message varchar(500),
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  delivered_at timestamp
);
CREATE INDEX IF NOT EXISTS idx_brochure_delivery_reference ON brochure_delivery_attempts (reference_number);
CREATE INDEX IF NOT EXISTS idx_brochure_delivery_status ON brochure_delivery_attempts (status);
CREATE INDEX IF NOT EXISTS idx_brochure_delivery_created ON brochure_delivery_attempts (created_at);

DROP VIEW IF EXISTS public_search_index;
DROP VIEW IF EXISTS public_masterplan_zones;
DROP VIEW IF EXISTS public_collections;
DROP VIEW IF EXISTS public_properties;
DROP VIEW IF EXISTS campaign_performance;
DROP VIEW IF EXISTS sales_follow_up_queue;
DROP VIEW IF EXISTS admin_lead_summary;

CREATE VIEW public_properties AS
SELECT
  p.id,
  p.slug,
  p.title,
  pc.title AS collection,
  pc.slug AS collection_slug,
  mz.title AS zone,
  mz.slug AS zone_slug,
  p.property_type,
  p.bedrooms,
  p.price_label,
  p.status,
  p.hero_image,
  p.description,
  COALESCE(
    jsonb_agg(DISTINCT pf.feature) FILTER (WHERE pf.feature IS NOT NULL),
    '[]'::jsonb
  ) AS features,
  COALESCE(
    jsonb_agg(DISTINCT jsonb_build_object('type', pm.media_type, 'url', pm.url, 'alt', pm.alt_text, 'is_primary', pm.is_primary, 'sort_order', pm.sort_order)) FILTER (WHERE pm.id IS NOT NULL),
    '[]'::jsonb
  ) AS media,
  COALESCE(
    jsonb_agg(DISTINCT jsonb_build_object('name', fp.name, 'bedrooms', fp.bedrooms, 'size_sqm', fp.size_sqm, 'url', fp.url, 'sort_order', fp.sort_order)) FILTER (WHERE fp.id IS NOT NULL),
    '[]'::jsonb
  ) AS floor_plans,
  p.created_at,
  p.updated_at,
  p.id AS sort_order
FROM properties p
LEFT JOIN property_collections pc ON pc.id = p.collection_id
LEFT JOIN masterplan_zones mz ON mz.slug = pc.slug
LEFT JOIN property_features pf ON pf.property_id = p.id
LEFT JOIN property_media pm ON pm.property_id = p.id
LEFT JOIN floor_plans fp ON fp.property_id = p.id
GROUP BY p.id, pc.title, pc.slug, mz.title, mz.slug;

CREATE VIEW public_collections AS
SELECT
  pc.slug,
  pc.title,
  pc.description,
  pc.status,
  pc.sort_order,
  COUNT(p.id)::integer AS property_count
FROM property_collections pc
LEFT JOIN properties p ON p.collection_id = pc.id AND p.status = 'published'
GROUP BY pc.id;

CREATE VIEW public_masterplan_zones AS
SELECT
  slug,
  title,
  description,
  image_url,
  related_collections,
  status,
  sort_order
FROM masterplan_zones;

CREATE VIEW public_search_index AS
SELECT 'property'::text AS type, title, slug, description AS excerpt, description AS content, status
FROM properties
UNION ALL
SELECT 'collection'::text AS type, title, slug, description AS excerpt, description AS content, status
FROM property_collections
UNION ALL
SELECT 'masterplan_zone'::text AS type, title, slug, description AS excerpt, description AS content, status
FROM masterplan_zones;

CREATE VIEW admin_lead_summary AS
SELECT
  l.id AS lead_id,
  COALESCE(l.reference_number, latest_enquiry.reference_number) AS reference,
  COALESCE(c.full_name, l.name) AS customer,
  COALESCE(c.email, l.email) AS email,
  COALESCE(c.phone, l.phone) AS phone,
  COALESCE(
    l.property_interest,
    l.property_interests ->> 0,
    'General Roho'
  ) AS interest,
  COALESCE(l.source_platform, l.utm_source, 'Direct') AS source,
  COALESCE(l.campaign_name, l.utm_campaign) AS campaign,
  COALESCE(l.lead_status, l.follow_up_status) AS status,
  su.full_name AS assigned_staff,
  GREATEST(COALESCE(l.lead_score, 0), COALESCE(l.score, 0)) AS lead_score,
  l.created_at AS created_date,
  l.next_follow_up_at AS next_follow_up
FROM leads l
LEFT JOIN customers c ON c.id = l.customer_id
LEFT JOIN staff_users su ON su.id = l.assigned_salesperson_id
LEFT JOIN (
  SELECT DISTINCT ON (lead_id) lead_id, reference_number
  FROM enquiries
  WHERE lead_id IS NOT NULL
  ORDER BY lead_id, id DESC
) latest_enquiry ON latest_enquiry.lead_id = l.id;

CREATE VIEW sales_follow_up_queue AS
SELECT
  l.id AS lead_id,
  COALESCE(l.reference_number, latest_enquiry.reference_number) AS reference,
  COALESCE(c.full_name, l.name) AS customer,
  su.full_name AS assigned_salesperson,
  l.next_follow_up_at AS follow_up_due_at,
  COALESCE(l.lead_status, l.follow_up_status) AS current_status,
  MAX(la.created_at) AS last_activity_at,
  CASE WHEN l.next_follow_up_at IS NOT NULL AND l.next_follow_up_at < CURRENT_TIMESTAMP THEN true ELSE false END AS is_overdue
FROM leads l
LEFT JOIN customers c ON c.id = l.customer_id
LEFT JOIN staff_users su ON su.id = l.assigned_salesperson_id
LEFT JOIN lead_activities la ON la.lead_id = l.id
LEFT JOIN (
  SELECT DISTINCT ON (lead_id) lead_id, reference_number
  FROM enquiries
  WHERE lead_id IS NOT NULL
  ORDER BY lead_id, id DESC
) latest_enquiry ON latest_enquiry.lead_id = l.id
GROUP BY l.id, latest_enquiry.reference_number, c.full_name, l.name, su.full_name, l.next_follow_up_at, l.lead_status, l.follow_up_status;

CREATE VIEW campaign_performance AS
SELECT
  COALESCE(l.utm_source, l.source_platform, 'direct') AS source,
  COALESCE(l.utm_campaign, l.campaign_name, 'none') AS campaign,
  COUNT(DISTINCT l.id) AS leads,
  COUNT(DISTINCT e.id) AS enquiries,
  AVG(GREATEST(COALESCE(l.lead_score, 0), COALESCE(l.score, 0))) AS average_score
FROM leads l
LEFT JOIN enquiries e ON e.lead_id = l.id
GROUP BY source, campaign;
