-- 020_enquiry_pipeline_compatibility.sql
-- Idempotent compatibility migration for the public enquiry pipeline.
-- This exists because CREATE TABLE IF NOT EXISTS does not add newly required
-- columns to databases that were initialized with an earlier schema snapshot.

CREATE TABLE IF NOT EXISTS enquiry_reference_sequence (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS customers
  ADD COLUMN IF NOT EXISTS full_name varchar(160),
  ADD COLUMN IF NOT EXISTS email varchar(254),
  ADD COLUMN IF NOT EXISTS phone varchar(40),
  ADD COLUMN IF NOT EXISTS country varchar(100),
  ADD COLUMN IF NOT EXISTS preferred_language varchar(60),
  ADD COLUMN IF NOT EXISTS preferred_contact_method varchar(60),
  ADD COLUMN IF NOT EXISTS marketing_consent boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS privacy_consent boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE IF EXISTS leads
  ADD COLUMN IF NOT EXISTS reference_number varchar(40),
  ADD COLUMN IF NOT EXISTS customer_id integer,
  ADD COLUMN IF NOT EXISTS anonymous_session_id varchar(120),
  ADD COLUMN IF NOT EXISTS name varchar(160),
  ADD COLUMN IF NOT EXISTS email varchar(254),
  ADD COLUMN IF NOT EXISTS phone varchar(40),
  ADD COLUMN IF NOT EXISTS property_interest varchar(180),
  ADD COLUMN IF NOT EXISTS property_interests jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS collection_interests jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS bedroom_preference varchar(80),
  ADD COLUMN IF NOT EXISTS budget_range varchar(100),
  ADD COLUMN IF NOT EXISTS buying_purpose varchar(120),
  ADD COLUMN IF NOT EXISTS purchase_timeframe varchar(80),
  ADD COLUMN IF NOT EXISTS score integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lead_score integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS follow_up_status varchar(80) NOT NULL DEFAULT 'new',
  ADD COLUMN IF NOT EXISTS lead_status varchar(80) NOT NULL DEFAULT 'New',
  ADD COLUMN IF NOT EXISTS source_platform varchar(80),
  ADD COLUMN IF NOT EXISTS campaign_name varchar(120),
  ADD COLUMN IF NOT EXISTS utm_source varchar(80),
  ADD COLUMN IF NOT EXISTS utm_medium varchar(80),
  ADD COLUMN IF NOT EXISTS utm_campaign varchar(120),
  ADD COLUMN IF NOT EXISTS utm_content varchar(120),
  ADD COLUMN IF NOT EXISTS utm_term varchar(120),
  ADD COLUMN IF NOT EXISTS landing_page varchar(300),
  ADD COLUMN IF NOT EXISTS referral_url varchar(500),
  ADD COLUMN IF NOT EXISTS last_activity_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE IF EXISTS enquiries
  ADD COLUMN IF NOT EXISTS reference_number varchar(40),
  ADD COLUMN IF NOT EXISTS lead_id integer,
  ADD COLUMN IF NOT EXISTS enquiry_type varchar(80),
  ADD COLUMN IF NOT EXISTS message text,
  ADD COLUMN IF NOT EXISTS preferred_contact_time varchar(120),
  ADD COLUMN IF NOT EXISTS payload jsonb,
  ADD COLUMN IF NOT EXISTS score integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS follow_up_status varchar(80),
  ADD COLUMN IF NOT EXISTS notification_status varchar(80),
  ADD COLUMN IF NOT EXISTS status varchar(60) NOT NULL DEFAULT 'new',
  ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS lead_activities (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id integer NOT NULL REFERENCES leads(id),
  reference_number varchar(40),
  activity_type varchar(80) NOT NULL,
  summary text NOT NULL,
  campaign jsonb,
  created_by_staff_id integer REFERENCES staff_users(id) ON DELETE SET NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS lead_activities
  ADD COLUMN IF NOT EXISTS reference_number varchar(40),
  ADD COLUMN IF NOT EXISTS activity_type varchar(80),
  ADD COLUMN IF NOT EXISTS summary text,
  ADD COLUMN IF NOT EXISTS campaign jsonb,
  ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_customers_email ON customers (email);
CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers (phone);
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads (email);
CREATE INDEX IF NOT EXISTS idx_leads_phone ON leads (phone);
CREATE INDEX IF NOT EXISTS idx_leads_anonymous_session ON leads (anonymous_session_id);
CREATE INDEX IF NOT EXISTS idx_leads_status_score ON leads (lead_status, lead_score);
CREATE INDEX IF NOT EXISTS idx_enquiries_created ON enquiries (created_at);
CREATE INDEX IF NOT EXISTS idx_lead_activities_lead ON lead_activities (lead_id);
